version: '3.7'

services:
  parser:
    build: ./parser
    restart: unless-stopped
    ports:
      - 80:5000
    expose:
      - 80
      # - 5000
    volumes:
      - ./parser/src:/app
      - ./app-volume:/app/app-volume
      # - /etc/localtime:/etc/localtime:ro
    # env_file:
    #   - ./env/parser
    # networks:
    #   - flask
    #   - db

  # mongo:
  #   image: mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   networks:
  #     - db

  amass:
    image: caffix/amass:latest
    volumes:
      - ./app-volume:/amass/
    ports:
      - 8000:8000
    command: 'enum -o amass/scan.txt -d example.com'
    user: root

# networks:
#   flask:
#   db:
