# Use the official MongoDB image as the base
FROM mongo:latest

# Optional: Set environment variables
#ENV MONGO_INITDB_ROOT_USERNAME root
#ENV MONGO_INITDB_ROOT_PASSWORD example

# Optional: Copy initialization scripts
#COPY init-mongo.js /docker-entrypoint-initdb.d/

# Expose the MongoDB port
EXPOSE 27017